project_name: aareguru
builds:
    - env:
      - CGO_ENABLED=0
    binary: aareguru
    goos:
      - linux
      - darwin
#      - windows
    goarch:
#      - 386
      - amd64
#      - arm
#      - arm64
brew:
  github:
    owner: gexclaude
    name: homebrew-tap
  folder: Formula
  homepage:  https://aare.guru/
  description: aare.guru Aaretemperatur & Wetter & Sonne fürs Aareschwimmen - Chills mau wider chli
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
