project_name: aareguru
builds:
- env:
    - CGO_ENABLED=0
  binary: aareguru
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
  -
  # create zip for windows
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  -
    vendor: aare.guru
    homepage: https://aare.guru/
    maintainer: Claude <claude.gex@codeblock.ch>
    description: aare.guru Aaretemperatur & Wetter & Sonne fürs Aareschwimmen - Chills mau wider chli
  
    license: Apache 2.0
  
    # Formats to be generated.
    formats:
      - deb
      - rpm
brews:
  -
    tap:
      owner: gexclaude
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    folder: Formula
    homepage:  https://aare.guru/
    description: aare.guru Aaretemperatur & Wetter & Sonne fürs Aareschwimmen - Chills mau wider chli
scoop:
  bucket:
    owner: gexclaude
    name: scoop-bucket
  commit_author:
    name: goreleaserbot
    email: contact@codeblock.ch
  homepage: "https://aare.guru/"
  description: "aare.guru Aaretemperatur & Wetter & Sonne fürs Aareschwimmen - Chills mau wider chli"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
